version: "3.8"

services:
    server:
        build: .
        ports:
            - "8080:8080"

    grafana:
        image: grafana/grafana:7.5.3
        ports:
            - "3000:3000"
        networks:
            - grafana
        volumes:
            - grafana_data:/var/lib/grafana
            - ./docker/grafana:/etc/grafana/provisioning
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_BASIC_ENABLED=false
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

    influxdb:
        image: influxdb:1.8
        ports:
            - "8086:8086"
        networks:
            - grafana
        volumes:
            - influxdb_data:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=load

networks:
    grafana:

volumes:
    grafana_data:
    influxdb_data: